"""Initial SignalDesk foundation

Revision ID: 4dd05af03a50
Revises: 
Create Date: 2026-06-07 22:19:20.444556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd05af03a50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('insight_type', sa.String(length=120), nullable=False),
    sa.Column('business_area', sa.String(length=160), nullable=True),
    sa.Column('category', sa.String(length=160), nullable=True),
    sa.Column('severity', sa.String(length=80), nullable=True),
    sa.Column('confidence', sa.String(length=80), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('buyer_relevance', sa.Text(), nullable=True),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trend', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insights_business_area'), ['business_area'], unique=False)
        batch_op.create_index(batch_op.f('ix_insights_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_insights_insight_type'), ['insight_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_insights_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_insights_status'), ['status'], unique=False)

    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=180), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('object_type', sa.String(length=120), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('ip_address', sa.String(length=80), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('stored_filename', sa.String(length=500), nullable=False),
    sa.Column('file_ext', sa.String(length=40), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=120), nullable=True),
    sa.Column('upload_method', sa.String(length=80), nullable=False),
    sa.Column('parent_file_id', sa.Integer(), nullable=True),
    sa.Column('processing_status', sa.String(length=80), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('document_category', sa.String(length=160), nullable=True),
    sa.Column('business_area', sa.String(length=160), nullable=True),
    sa.Column('sensitivity_level', sa.String(length=80), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_file_id'], ['source_files.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256_hash', 'file_size', name='uq_source_file_hash_size')
    )
    with op.batch_alter_table('source_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_files_business_area'), ['business_area'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_files_document_category'), ['document_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_files_file_ext'), ['file_ext'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_files_processing_status'), ['processing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_files_sha256_hash'), ['sha256_hash'], unique=False)

    op.create_table('ai_processing_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('run_type', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('model_name', sa.String(length=160), nullable=False),
    sa.Column('prompt_version', sa.String(length=120), nullable=True),
    sa.Column('input_token_estimate', sa.Integer(), nullable=False),
    sa.Column('output_token_estimate', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('model_name', sa.String(length=160), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('detailed_summary', sa.Text(), nullable=True),
    sa.Column('key_points_json', sa.JSON(), nullable=True),
    sa.Column('decisions_json', sa.JSON(), nullable=True),
    sa.Column('actions_json', sa.JSON(), nullable=True),
    sa.Column('risks_json', sa.JSON(), nullable=True),
    sa.Column('opportunities_json', sa.JSON(), nullable=True),
    sa.Column('entities_json', sa.JSON(), nullable=True),
    sa.Column('due_diligence_json', sa.JSON(), nullable=True),
    sa.Column('buyer_questions_json', sa.JSON(), nullable=True),
    sa.Column('evidence_strength', sa.String(length=80), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('sheet_name', sa.String(length=255), nullable=True),
    sa.Column('slide_number', sa.Integer(), nullable=True),
    sa.Column('email_section', sa.String(length=120), nullable=True),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('extracted_text_path', sa.Text(), nullable=True),
    sa.Column('text_preview', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('extraction_method', sa.String(length=120), nullable=True),
    sa.Column('extraction_status', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('risk_type', sa.String(length=160), nullable=True),
    sa.Column('business_area', sa.String(length=160), nullable=True),
    sa.Column('severity', sa.String(length=80), nullable=True),
    sa.Column('confidence', sa.String(length=80), nullable=True),
    sa.Column('likelihood', sa.String(length=80), nullable=True),
    sa.Column('impact', sa.String(length=80), nullable=True),
    sa.Column('valuation_impact', sa.String(length=80), nullable=True),
    sa.Column('buyer_relevance', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('mitigation', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('related_insight_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['related_insight_id'], ['insights.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_flags_business_area'), ['business_area'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_flags_risk_type'), ['risk_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_flags_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_flags_status'), ['status'], unique=False)

    op.create_table('action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('business_area', sa.String(length=160), nullable=True),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('document_chunk_id', sa.Integer(), nullable=True),
    sa.Column('related_insight_id', sa.Integer(), nullable=True),
    sa.Column('source_snippet', sa.Text(), nullable=True),
    sa.Column('created_by_ai', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['related_insight_id'], ['insights.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_items_business_area'), ['business_area'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_items_status'), ['status'], unique=False)

    op.create_table('insight_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insight_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('document_chunk_id', sa.Integer(), nullable=True),
    sa.Column('evidence_snippet', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('sheet_name', sa.String(length=255), nullable=True),
    sa.Column('slide_number', sa.Integer(), nullable=True),
    sa.Column('email_section', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insight_evidence')
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_items_status'))
        batch_op.drop_index(batch_op.f('ix_action_items_business_area'))

    op.drop_table('action_items')
    with op.batch_alter_table('risk_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_flags_status'))
        batch_op.drop_index(batch_op.f('ix_risk_flags_severity'))
        batch_op.drop_index(batch_op.f('ix_risk_flags_risk_type'))
        batch_op.drop_index(batch_op.f('ix_risk_flags_business_area'))

    op.drop_table('risk_flags')
    op.drop_table('processing_logs')
    op.drop_table('document_texts')
    op.drop_table('document_chunks')
    op.drop_table('document_analyses')
    op.drop_table('ai_processing_runs')
    with op.batch_alter_table('source_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_files_sha256_hash'))
        batch_op.drop_index(batch_op.f('ix_source_files_processing_status'))
        batch_op.drop_index(batch_op.f('ix_source_files_file_ext'))
        batch_op.drop_index(batch_op.f('ix_source_files_document_category'))
        batch_op.drop_index(batch_op.f('ix_source_files_business_area'))

    op.drop_table('source_files')
    op.drop_table('login_audits')
    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))

    op.drop_table('system_settings')
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insights_status'))
        batch_op.drop_index(batch_op.f('ix_insights_severity'))
        batch_op.drop_index(batch_op.f('ix_insights_insight_type'))
        batch_op.drop_index(batch_op.f('ix_insights_category'))
        batch_op.drop_index(batch_op.f('ix_insights_business_area'))

    op.drop_table('insights')
    # ### end Alembic commands ###
