"""Add daily briefings

Revision ID: dbbd111d0b76
Revises: e0380e88ebe7
Create Date: 2026-06-08 11:02:11.044347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbbd111d0b76'
down_revision = 'e0380e88ebe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_briefings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('briefing_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('highlights_json', sa.JSON(), nullable=True),
    sa.Column('risks_json', sa.JSON(), nullable=True),
    sa.Column('opportunities_json', sa.JSON(), nullable=True),
    sa.Column('actions_json', sa.JSON(), nullable=True),
    sa.Column('exit_readiness_json', sa.JSON(), nullable=True),
    sa.Column('source_file_ids_json', sa.JSON(), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('model_name', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('briefing_date', name='uq_daily_briefing_date')
    )
    with op.batch_alter_table('daily_briefings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_briefings_briefing_date'), ['briefing_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_briefings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_briefings_briefing_date'))

    op.drop_table('daily_briefings')
    # ### end Alembic commands ###
