"""Add extraction and email parsing models

Revision ID: e0380e88ebe7
Revises: 4dd05af03a50
Create Date: 2026-06-07 22:29:46.915531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0380e88ebe7'
down_revision = '4dd05af03a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=500), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html_path', sa.Text(), nullable=True),
    sa.Column('thread_key', sa.String(length=500), nullable=True),
    sa.Column('response_needed', sa.Boolean(), nullable=False),
    sa.Column('urgency_level', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_messages_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_messages_sender_email'), ['sender_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_messages_thread_key'), ['thread_key'], unique=False)

    op.create_table('email_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_message_id', sa.Integer(), nullable=False),
    sa.Column('draft_type', sa.String(length=120), nullable=True),
    sa.Column('tone', sa.String(length=120), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('ai_provider', sa.String(length=80), nullable=True),
    sa.Column('ai_model', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_message_id'], ['email_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_message_id', sa.Integer(), nullable=False),
    sa.Column('recipient_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_message_id'], ['email_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_recipients_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_recipients_email'))

    op.drop_table('email_recipients')
    op.drop_table('email_drafts')
    with op.batch_alter_table('email_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_messages_thread_key'))
        batch_op.drop_index(batch_op.f('ix_email_messages_sender_email'))
        batch_op.drop_index(batch_op.f('ix_email_messages_message_id'))

    op.drop_table('email_messages')
    # ### end Alembic commands ###
